### PR TITLE
[ENH] Add duecredit, move tedana functions to utils, and some light refactoring.

### PR DESCRIPTION
**Pull request by tsalo**
- I added duecredit to the package, as well as citations for the Dice similarity index.
    - Actually, I also changed the underlying code for `utils.dice` to be more explicit based on a great [gist](https://gist.github.com/brunodoamaral/e130b4e97aa4ebc468225b7ce39b3137).
- I changed the arguments for `tedana.do_svm` to match sklearn's [convention](https://github.com/scikit-learn/scikit-learn/blob/f3320a6f/sklearn/svm/base.py#L293). I also changed the documentation somewhat to (hopefully) match sklearn's.
- I added in some argument checks for rankvec.
- Other than that, I just did some light refactoring. Mostly splitting long lines and cleaning up whitespace. The `pcscore` definition in `tedana.tedpca`, in particular, was a couple of very long lines. I took the chunks from that and created new variables for them. The variables are all named `temp[0:9]`, which will need to be changed, but I think it's more readable overall.

### CODE REVIEW

**Comment by emdupre** [comment]
This looks really great ! Should `duecredit` also be added to requirements.txt, or does the stub file take care of that?

**Comment by tsalo** [comment]
I think the stub makes duecredit optional.

**Comment by emdupre** [comment]
Perfect. I know that the tests are currently failing for unrelated reasons, but did you have a chance to run `tedana` locally and confirm that it works?

**Comment by tsalo** [comment]
Not yet, but I will.

**Comment by tsalo** [comment]
I'm getting this error when I try to build the Docker container to test tedana:
```
Downloading AFNI ...
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
The command '/bin/sh -c apt-get update -qq && apt-get install -yq --no-install-recommends ed gsl-bin libglu1-mesa-dev libglib2.0-0 libglw1-mesa     libgomp1 libjpeg62 libxm4 netpbm tcsh xfonts-base xvfb     && libs_path=/usr/lib/x86_64-linux-gnu     && if [ -f $libs_path/libgsl.so.19 ]; then            ln $libs_path/libgsl.so.19 $libs_path/libgsl.so.0;        fi     && apt-get install -yq --no-install-recommends libxp6     || /bin/bash -c "        curl --retry 5 -o /tmp/libxp6.deb -sSL http://mirrors.kernel.org/debian/pool/main/libx/libxp/libxp6_1.0.2-2_amd64.deb        && dpkg -i /tmp/libxp6.deb && rm -f /tmp/libxp6.deb"     && apt-get install -yq --no-install-recommends libpng12-0     || /bin/bash -c "        curl -o /tmp/libpng12.deb -sSL http://mirrors.kernel.org/debian/pool/main/libp/libpng/libpng12-0_1.2.49-1%2Bdeb7u2_amd64.deb        && dpkg -i /tmp/libpng12.deb && rm -f /tmp/libpng12.deb"     && apt-get install -yq --no-install-recommends     	r-base-dev r-cran-rmpi      || /bin/bash -c "         curl -o /tmp/install_R.sh -sSL https://gist.githubusercontent.com/kaczmarj/8e3792ae1af70b03788163c44f453b43/raw/0577c62e4771236adf0191c826a25249eb69a130/R_installer_debian_ubuntu.sh         && /bin/bash /tmp/install_R.sh"     && apt-get clean     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*     && echo "Downloading AFNI ..."     && mkdir -p /opt/afni     && curl -sSL --retry 5 https://afni.nimh.nih.gov/pub/dist/tgz/linux_openmp_64.tgz     | tar zx -C /opt/afni --strip-components=1     && /opt/afni/rPkgsInstall -pkgs ALL     && rm -rf /tmp/*' returned a non-zero code: 2
```

Any idea why?

**Comment by emdupre** [comment]
I had that error once, and restarting docker fixed the problem! Let me know if that doesn't work for you. 
If you'd prefer, you could also use `docker pull emdupre/meica-docker:0.0.1` to grab the image from dockerhub.

**Comment by emdupre** [comment]
Thanks, @tsalo! 🎉

**Pull request merged**
